apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mtrack-secrets
  namespace: mtrack
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgCI2BPfUipqyPnM+UeHdurtfKDusV+79BsARxcOyX+3f9XYWqu0z/N9uJK3TRW296nRCSmJH93n4aE2QgYGUU6b7YzXtKgrAzbkXPooqgQdJwc7uTZ9jjOFiYKP2zKHZrMWIBtzo/qxwcRqt3Quutml4XZWGzJtqZP840ZnFMBsvgiCRIiixvXdD/6PzZ0ujdGNWCnPoCHSS4BdVdczThdBiFmQIaR6wrOxYDd9cVF3DzaK9wee0PvK8HWFWobOcWVYBHV7MwLI39zje60pQSB4Myn3IBFVbF7YwNuXSnvSRlc9/9zRjwNBVZHXoI4wnu6wjzPBd5Qm41RwC/Xgm34LkoYrRly/ntJ0BlvI1XgI6PX+jHU/qLPAHFGmpwWIo8M7gQGMO5nHRR4kK7uWEd/ZjHbOS5UhsphXaGO0o51Si9kRouV1L+OzEMLQcRt5mP8su6ZAV60ZCh4pOHQ4ksHw+D8Rj+EWY3E8D1cR2vIdPV8Gmt2Ms6Z0E7ESia8BsQ34sYyHZjtVeX5Wp5EPnj/BKCI98kDM97nilhHyeKeB/5utl/hOXMIcIwstHbXHJddxAMwH+m55BeE9etp5x3QO/8/ocu3gcaVArPAImXKmaLbajIr2QSsk6Zbkkhr3jE8z5kWvDMG5BjU3BTlrxYkpg2oGDlRaf6TQcRCwhvO2hqPWlD3mBrTbb939l4mQniYrnERwCba1qoqLQFqj
    POSTGRESQL_USER: AgCCL7j1qEOug5UzNnGOAiXNSk/GUZvYNzWXYIQB2Bm5zm+OIY/4kBO05uxkX8HwmahdY2rBqNN7PPSLmZ6EOdPme3ZD94gYSqEP8jMTFEVowEyh+faVup+jGV4/KIjMR3RKAcsn4c/l7dYq4Bkl9g/lXBWiISiNwm4/ZtluBZ9Q1PvX4CEIgst4XzI0X/JO4TvdkDs0sk1EMWjLRPsGwd800w5VpJ8o9SsE1gnf38vP3t5YwDRWu/CPRx1YV5EdGwU/YRz93PU5x/cuGzUQRGr1S18z7aha05Bn/kLNMWuUkxH2r29knZfvrTicH2gNghZfEHkEFAfugI/nMzzur9xaq0jO6KGIqeh43xdDEaWVIsL+JvN89sn4yADM3+OZOMTn2oOHkHr2knW36dhnVoobHHBAywlyVep6wR1qpW6f3vXKFYBHWz6xWMmNlkv9jpLC5G2pM+mtNH5nKDUo4TAOdkCZa2sp/ItV83Jmv5uzZOzm12+cyO+81axWuUP8vK/Axdgil6YOBeu7r9okN/b/r5t4XnrpU5kHRTvUlI6stveblN+I9V5FviLBSjEhEyrvPwx6JSH5qtviq2uicdvX/00s3pfv0qOYo70kQz0C95jVun8oZ4SJMuN3IL5Rau7BXYMBhbKf9+mYmgT22dWApfgzNQO2mbeb7+fH8oJPN+2oLRIRWTFDjVrQ0caHnF7I6ASLXAQ0
  template:
    metadata:
      creationTimestamp: null
      name: mtrack-secrets
      namespace: mtrack