apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-secrets
  namespace: registry
spec:
  encryptedData:
    password: AgAV93pyd0V0kX2AY+orqJYIfVtmZaNmujYuaetp78QLyY8+RGRNgpnVKSCeGnQzds9fi7uQF3wifuUubmMY8cQ6S+Ug3oB/WYxGVtiYGnA2qDIJCXF/W1hLDyc33ZQ0jqVIUxEmAekNHN63baHQ5+i6YzvzLfHGSLXBA/XOIiq1vN08SgI8d/1VUmCO2MYTlwu/s+T8hzV4gW4uPNznEDp6rPwLTOYK5SnA2z2QIfTuYaiCpgdHsHJGxPGwmavCiXggaTzPocToWrw9Nr7a0on+0PtevEIUY73/q4OKOR5rzMaDt8qfXjXnQNKCmOoaGvLOI43a/CfR5F2P0+zPd3QsF9E48oAXbyvOo2drgXp6GXs2QqZy6aVYUkN/33rUXqtAcNxwzqXZYyGDl4S9rxNFNsBXGWOy6vz3YFebxcpz7tRY88vaAVZWvtODqadAjfjPQBaGblu9tIHaySap+5DItSKGBzEiby1kTVHzBMFCEnQvyzdum+P/n0+ax41rQFngdMN2dO8XykMhgdog+okZ/hXJUJYf+WBlvWGN24X8+IWiXYrIDGW19NDpV8z/dccOSWf3TMAUt2PGD2NeSKGrtyz4X4/9w1JF00ftMI79OhXAjjCF21tYanBz43Aya1qAmgQWbn+HR7BnO2EbV7RD5cqH0rUtvqPVTlCxyoaGxXP/xt7EoT1ag0YJpk0y4MnevJhAuFJxbZwR
    username: AgBid7jX/1Nhbx9xGW+mlIUpc7o8a9bA6ypg0sKKlYmbyEmRww6x+pYr0VAFrv65Du2LPNTQpfpRW3pMKgDlkGV6FAmsgWiF8fWs+hLZ2QQXfZKkA1GQ4SNXVezbZUG/zxFlRKMVK8TLqAR8N/+zxcrliSLJkrF2knKVhv5tMLNzUoc6ggT/BKnz8e0wgww9oiwoh0x2mJFHHhujmIUH5htHarzQnja6Z0TPeS1Ond8BYCVZgiuT4wh3UV7XcoGCBHqTmMfnYSlpJLqvoEY4CwlIb9v9VZRkkFbetKN/zBLO/QKfCZFDOTf9D0zRR2hePInKsmb6TotfYq44kkepTeXbuVznueOXciYtlACG/pUHl1S/efHi+PQA2xUPgsqaDXl/OnxWTaSaudPxxnEpJf64AUK6f6v7MhgWY+3Vuayp87oxMHBIveHJ/aAHvFiUJrIklF20ap9Hn7rAbJbrC5CsSAq4UddytIUw6LlfYbhSa86DzMzbyzaM8CbHTPcI77kHDC+IKxZEQn+GbXvLXG7YLt9FtO2joRPMWKXUS7fNqewRgTFSZVOom2GRsm3coAFGV/12znSSbMGQ54/MlVFPh++sYtSzNisT/aCZTLGlEXOURxq5XUnMzBnpJzSNFEqeZ6GtgW8kRqSqqC2yNHCdYbDTpGZTDtx+qbgykB5oULoga36KFrOLt2V/FIfXSBn+ZTbkcwyl
  template:
    metadata:
      creationTimestamp: null
      name: registry-secrets
      namespace: registry