apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.16.2
      helm:
        valueFiles:
          - $values/infra/sealed-secrets/values.yaml
    - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    # Deploy to kube-system namespace for compatibility with kubeseal CLI default behavior
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true