apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: https://charts.goauthentik.io
    chart: authentik  
    targetRevision: 2025.8.1
    helm:
      valueFiles:
      - $values/infra/authentik/values.yaml
  - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
    targetRevision: HEAD
    ref: values
  - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
    targetRevision: HEAD
    path: infra/authentik/config
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true