global:
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "authentik"

authentik:
  enabled: false

server:
  envFrom:
  - secretRef:
      name: authentik
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare-production-cluster-issuer"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - auth.agogi.dev
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: authentik-tls
        hosts:
          - auth.agogi.dev

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

worker:
  envFrom:
  - secretRef:
      name: authentik

postgresql:
  enabled: true
  auth:
    username: authentik
    database: authentik
    existingSecret: authentik
    secretKeys:
      adminPasswordKey: postgresql-password
      userPasswordKey: postgresql-password
      replicationPasswordKey: postgresql-replication-password
  primary:
    persistence:
      enabled: true
      size: 8Gi

redis:
  enabled: true
  auth:
    enabled: true
    existingSecret: authentik
    existingSecretPasswordKey: redis-password
  primary:
    persistence:
      enabled: true
      size: 8Gi