apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.16.2
      helm:
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
      targetRevision: master
      ref: values
    - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
      targetRevision: master
      path: infra/cert-manager/config
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
