apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
    targetRevision: HEAD
    ref: values
  - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
    targetRevision: HEAD
    path: infra/registry/config
  - repoURL: https://helm.twun.io
    chart: docker-registry
    targetRevision: 2.2.2
    helm:
      valueFiles:
      - $values/infra/registry/values.yaml
  - repoURL: git@github.com:AgostaGiorgio/HomeLab.git
    targetRevision: HEAD
    path: infra/registry/ui
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true