# values-registry.yaml

replicaCount: 1

image:
  repository: registry
  tag: 2.8.3
  pullPolicy: IfNotPresent

service:
  name: docker-registry
  type: ClusterIP
  port: 5000

## Storage
persistence:
  enabled: true
  existingClaim: registry-pvc
  accessMode: ReadWriteOnce
  size: 500Gi  # match your PV/PVC

## Authentication
auth:
  enabled: true
  htpasswd:
    existingSecret: registry-secrets
    path: /auth/htpasswd
  # Optional realm name
  realm: basic-realm

## Registry configuration
configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
    filesystem:
      rootdirectory: /var/lib/registry
    delete:
      enabled: true
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
      Access-Control-Allow-Origin: ['*']
      Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE', 'PUT']
      Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control', 'Content-Type']
      Access-Control-Allow-Credentials: [true]
      Access-Control-Expose-Headers: ['Docker-Content-Digest']

## Ingress
ingress:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi