persistence:
  enabled: true
  existingClaim: registry-pvc

service:
  type: ClusterIP
  port: 5000

secrets:
  existingSecret: registry-secrets
  usernameKey: username
  passwordKey: password

extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: registry-ingress
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-production-cluster-issuer
        traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
        traefik.ingress.kubernetes.io/router.tls: "true"
    spec:
      ingressClassName: traefik
      rules:
        - host: registry.agogi.dev
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: docker-registry
                    port:
                      number: 5000
      tls:
        - secretName: registry-agogi-tls
          hosts:
            - registry.agogi.dev
