config:
  registryUrl: https://registry.agogi.dev
  deleteImages: true

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  name: registry-ingress
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-production-cluster-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: registry.agogi.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: registry-agogi-tls
      hosts:
        - registry.agogi.dev
