apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: postgres
spec:
  encryptedData:
    password: AgBR/1S0zHUGIsGM0+12OBgauJHZbJSy1lnWWa0UQO+l2+W7MhYRuRCpUHHfYdz1/ScszHoiTCXwwZdQsEQxgw+emXdXOoNvmIaGmyaOsmAr8FFkhrvWtbQmIVeP4EM2A1/VIwwF8Z0U7ozQDmlPpIxJJLt2HwVekxlxehN4MuiVwh5wRvwKxSoFOcqPjW4F8exntgcYat6uKzw6cjHNGs1Hsffxd2soVozM8whYDrlbf7w8Ygc3oiChNDiiMtTT/mYk8fRn/1XUN1fwxE4QM2EyVsa9LzVou9KMGfZu5A8KMO7PS+dmPc/v6Ihp/2jnk0HZOVrkYY8yPReOCx4FC2KiCHZ0v5iawn/q+wk6bU5gfhlx2CSlPMCFFiGfX78847wAcarrGBqiqyGqAdP/j9Ex3K+S442aOx9H6etIdgvSXr4fYMeJKDDn5B/rXX/p+1O9bpoEnD72Z79zJRFzKz07T9WPHb0Qs/zQ02cLnFjtJ7m0yv4bc8sIEV2gIkso1hXRmTqkudTPwBN8OFRgqsnI29hPUJZBpCdmS9oVo2BvEKKl91INqiCcNtB50aHb2gg8aprD7lOch0I19TjMhXxDbI3NJdh5iR5ALdyz0uPBseaOApCquWXW51XEoaqFADvxmUBSG+M5+JNqGy6s8VOvFc5/bu2+DlXVSSpFKPSp/ktj1D5xM6Jj5gdVv1cIMsRoYxbZFgPkIxWVzkne
    postgres-password: AgAf5HzVaVSlzKbH6aotVgy0coTlUwsyJ3+yx29FAquPNbRnA47nf/7H3UEyGkIOablE73Y5/r6DebaFmrZcck2QVwmGOv9XOlEOIBU4iujhJ9PRxkP7qa5E/BfNl36qvcY+rzRv04v0fRk3qcHRNH7Xf9z9q4BI5Sqc0opJhtkFNzFD2+MgHyf/PvZEzb9fxldcAs7gzGfyAbzd2IV0jexZ0Ckss66v6yRIdt05e82YWGpLI8y/YrrPlQWEbQnUAVbEVCI6yXk9Dbg+PgxX5d0VeRH5QJs6e7Y5d24biGMz38BPhs2sjIyyj7amqvGc/gSk/S89qe1YuuLLtVQYRGXRF1Jz7uvum8xDzEmPuDr70W36OVf/It8PodIxljIaFkstXfokjBiljIX4fCn5m4CGN/WXIYYu4kzDe0NhtltA62ARxefCjsKSt9hwsic3BJhx0CZRLEdTdOEurnrTIUNy+SQR0zNJJv1OANBlth8O35D5qz8sxlrbsXmBlZtdeA/hymnv04THBi7JRtGGptSqnHJM/jXq/IVi95hVofWVAkL9Pzjr3OFbC/RWMb/X8KOkHx3YMQ2LnfhhFWpXYaDPagq5mPwJjzqU0eb3kml72HCeV5azvjzJZ1VwON4glAcLJoLRD3zuHj5bzEvP2znh7euepOEJ2Pj4YXLTOT1/BWTUyY+RN0bOHKn4D1V7y7IPJep63RfwzmF1/ykz22hBht1I
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: postgres