apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDIRNhxia3w3xi7X9X/zzPtwrREPt6VdY0IITpuq4RuoD5ZytLz0jR/mFvKiJsO+nN/NVM5UUO5ombq8GDj0POIA0JVtNZyAiNZmLNPWdcgGrzf8Tl/DzAVF3RDbAGIBgKeW3dJUB61tVele4ba50JK40aGv2xXQ1aKaIecOwSnJHLmc4gP7Z+6+4WaSyrl42p4KTZLI9RwAJZJ8b23SWKUUY+UwmSJBHDDLgxwWjyalLOjToxw5YV36c0yL/lDf59So+1rBaqK8WlTFih8iTouAIcxUCd6Yk+AhvIRJwvox+IdLMqD2oZS1r8IlQt+H22BHzRoUy0dSXQEx84xtqByPz4w9VWC1z04sDPBXXWGwjdAiwlRX+XCyGhRXYc/9MmtBBacgpb1oagMuhjb9bAiYJACHvlvCzV3fKMUo1ONbI810c1XUtwuHKQ3E4M6/ypg1LQ3a3VXw5Z76j9Y6sOQId8qRWMIMar5GzzOLinDIuNjmhzSH0hZ1YtmQ1cGgRgOjmZs3Cvz7aodHDRfXE9wAQt2pfv6su+7HMN2ftj1GeVzNGXGbb3Al4N7Ha1r8WIA8l0GcGI0doN680snB96kA1boV/U6dbYogwsybvbymEcvpyGSMH6Nf8ahFjzC5giRQ2/mE0HBJIaOGAb59MO1dYlBHlCveB3ikAFBqrBVMY5OVpzpUoOOvqNIOF/r5piOMjZHFVaXifjEiVcUFwMd3TXu5Ki9AGrJmdzC9wkx8bdeysF59COl
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager