apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-secrets
  namespace: s3
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgASApVeWVSqmJFVeQ4wWw5hFS/eIDR1siBy504Xjw0jTtMjXqj8AjqWvREPE47Uc9u7VLP6HFvDx3Oi/hsTZBcs38Y0PJySfXsALzCmd6aN/JOLD44HGaOH102nc2hoS46wto8KG+KMlX8+5Vux8Kiw8tDsShalLqF7yu+3LkIOxwrGelimnVGz+RS88FNcoAORzPk0oA7Fh5G1hV974SC2L73JmFCu99Jec5R1+YuB4Z+2Mo94RV/OoMC5vyYmgxgLmSTor2fSr4umGr6yyTCswHnexI/VWjZ6Jq5kWyrXR2SGljMxtn0sQZovOT9Pvfj2V2yjAWodOOoLJ5jC/DSQQrLuDODXemtLNOsl4l9Vpao5ktmdhk6Zn/VukqxBDRcXsnFoK5qffyC1araO1+XghapHfiGQKU8rDn/yTEwmt5R1f9Zsk8+wzH/YNJNjiN6s5T8IJ3U2/69gps/IXcdJ5dg56WYT8a2dmENLalYX8m2VM5sjHFZ2bsjDPVOLmCei6YCTu70jmDhKbKPTzEPpl3b15q7KblqxKRzu9wizEL2WN09m1rJO9xrZxvFuWNhe2dAeHxsFbqLd+mSaCItkHxCF7cnwkOZRvbPbVgTJQGgJHvcCRBKbtzwWNSlOxBLpAEvuW+s5O137ZIyFKm2fcIwdnOdDVfww+ar/IKPvfyW0AAH2UeuGkhDLEK0E5d/hEbazLf24ZfLXmB5wiz9zaU4kjA==
    RUSTFS_SECRET_KEY: AgAV+P24Tezh9oZaUYI1s/pZG/Xl2dxEVGcmPyPdMAHvx363+HhRXRQUrOMVjLL2Ki8rg3jl5YBzkNgD6Es+FqaU01nkSwau/TiHoOSsy6q4RuMQoltF9kMiM6tGegTOl78cY++YbXL3Rs9T+272JFkzL+ag9RA5eE7yQ5Y94V3BmvOP5tObbwuXPKYFOpkaVMjctet4nnJ3kZv2XsBzV+OYZExzDXQ3Cej09wrVpUgnaBHOC1ZEVc03bX8eMV1KkotBiRH2Gge4wpAtQJZv9hePq8LSR9t6Uvw+AvtzcqHQr6IQM+zzBtGlvjIm5gAWn6B6b/xuogEqu/F4nczXgRPAe74SSITu6aPKU3g35J7HPCuP0jYJ3h+V5khwG5hFltKMhkgtZhbUt83Rb4wo6LkFdyuZoN+KLkjmBveV5pe71R/Mi4iUnmYMTpz2nZVCyX32/YGNgNRIVlJwJkX8uOzr/TMcOOEe/9XJKBKIL3tJwdRH1+Xmiic/DGgyNkyIRLwF5XlDZS0zpTnu+NsCvGw1x+W8lRzx+NJgLu27NRRvfz7Kjfat+82ZywSHTR8MJFD3p+THQb0pVfgxmtu1d0JgUZ+Asnu2y1vZsG0rGNTXpKzmpTj2by/VLSmB5WzLOp9ISvR7erOgi2DDw7wBltSyvP2QK9jqh2wDHRaBNaOv7cGIwJNQeUT+757mxvpgKeVV7za4HN+BBhEKiTYB2qlFmyJawE3jMqWYmnzfZu+xzkh/bdeYHV0W
  template:
    metadata:
      creationTimestamp: null
      name: s3-secrets
      namespace: s3