apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myinves-secrets
  namespace: myinves
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgC8zQbiHuOFnj5DZLp46WarsB4ZMoCu5aU/LFp0NAqlrcVXMr+rw5kzkPyiAp07Wof4uBBpksf+urea83h438KZaSvkrKTScBk/7cXGf4nsxqGZznB7zpf/6K220sG2qfEUHkM5N34RWtCerm+ChgewAJ0zlylg5gEmlD6qOJYkGlZhqWh7olQqMaBlT6mn4sdSIFp3kOcfGlseYdwBVjXZ82WMrkXUDNB51yyE09rB+g19Qgk0peei2velOsHK3y9U4dTy0yRSLYs0zrw5+M9esU2KrzoMntmzZCu0zLP1Dm4vK331VgS4KXMF+2sgWgBE3VKayVka4cjbcKVddRN15SJebWtbb09EFBNMcEHkzFSCKiTrI9CSi19skD8vhOMEh7cCAijPgf4WLDm4Gg+qJs8jjpa6ioCUwtJNYpfbd77wvyX+vl45R/HDaWp2+89lZhlmMYCxJflB31XIIWoMMTfUnJ2G1x3F0k/ofsbvSIokBHsjdg3PL9ypLUXGWbOP23nsru470T7bTcRiXm8iMxyEVSz95PUcoSDyF0FOLbXS3xt1nu4qHE/gf2+YRx1+nooHibofr9kd8jadTyjynQpickjBBsHTYV1ea//a18MKa8Dic4qbFc2KFsXvJVekXqCOR6JUppw/RTNVcLyaKqBPdSRGgJdu8Cts2C4J/UyZim94/1rNajsp3AgjK8sSXmtri4r5bzH8N9Ss
    POSTGRESQL_USER: AgDAAqDNEXo1egeTvCOUO36Q5HkedoBpCcSnQFMV3zNRvPQ5+9urrlhI6csPV0NmfJAWhKHm7ZTAW6PSBy3n+xyXETS30Vk0X1bI6zexzERKOKSz/shJXY1t5MxBNQjpoylfoN4cWPYvFtZPUbFUQyVDbILwPBfT8trYXsElw3no4XtOcjizQem/yQrwNuQFh47pWFuBHw4+3Z4I8QT4BSm50CG/GgaJtfmZNaErIPxQerdtaSFKv/ESUOGKnItRDc8K58Iv/jqv/yKdCRf3TctbhYhI3z8GZN7RdsJ17SDlGRUh2Azom4fJiLiQNDKq/C+lISByQC7dqOtktdhxXYxPADc2I4D2W2dbN21o/gWVOdYzMPrddc32YO7u3chJ2Gopn8MdY9Gi3rVSCojBuZeFigRig/jQhG/QJu7iE0zDOE12R00XJGpxKPV8roDJbL4UCsFTuejPvmrKPXReKCoEwhnhiLV6C5M1Mp2mOZCWtHJvRvdTdlUuuZ86FqDyELweDxulTt7upVkYU47FjqFsSsCYunGxlA210P/wN4JDoGY/YP8RdL08TC7yXoieI+OgBfQUSh1gUTxVC8x7DX/EdDvj+8uyS0tsqIff6mgI75RIHD3TShQoDhKZXXF+tfOw5NYzKRHzxcWb1V6scqqXRM1R7iH4osKOG53nLhG5GY4IE+upEPreyOJwXWHL4iNExL2BlFYj
  template:
    metadata:
      creationTimestamp: null
      name: myinves-secrets
      namespace: myinves