apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: myinves-secrets
  namespace: myinves
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgBbx3EiceJkNZkXa9mWBpjLgQXlBALHt2KUo7cag41fBRpsyFoGGFaULYyQlqSW/puLIso/44t80HAQDjlbOAzelKs0t8Hz/1s+cOwwMQm5ErTxUJ3fZNKFbpZgYTW1aITWENMH5mLFxzoPmz6gUhE/IK5dkp8LN2CKIhSZ6iiqPdI4O+A/lXsgwkDHMMYIgIK0TRxp0MWI8M7t75P9tpK79RhsiHm6Y5vZc7/ZGP5v7zAMyylqy4cHXFVpT6wbhGeUAhq7/Wxc8XAOjnnx2rhn9/85+C50yjAV7CtSsdtHytPKTplzrItWXXuFIl96C38OR9N+W2mcvHtIK1wI3e7cch2UChD4H/MpJg1HXzfVaqLITfDf5am9srPMryOduYKXs9w6qGWjhHV8z0ZHZHDdyuiBMtUqBZRPImUFG636HnDSqnFIxuNpkmHBpK5UAO2ItCSRdWLyRjtST7d4lIZKSnZtwb84UxQrXZljH4nwHP8FevyeGgQPtQ3n1W9Z/1g5gAfEjrJLIzJny9cyNsqN25uy3/Ob5qjYLZGTzMn3eBXKZEOu5L3ht/GuD9iXCTEoBV8Nzk27iisARJQx+KFo4B7GgVIAXYXMhqoIJ1UY6y9vnI3MOhk9XvbbRkzuntOVvNZ/8f5NbLpyQwtpD7BV4ExwyuT5IELMhE3s8YNLXXTqsuiUdzAoNhXl2ljDD2b4MYFMbsNwE++2eGAo
    POSTGRESQL_USER: AgCkbyzO17Om9RQYCJk9rn2uuPyEFTOaSakSEzmMlCEGNjCf7b/U+CLKlhR7fCxwU433w9Zp4aLchl9woFe6thlDcpGkhIj+9AtTGbcVEpbxWMQK5KqVTiooit7wr67m5O4iUbAb3L3OGaVS/9VykuHsmKV5Adt80XSC9MDWmXekAazBQfmG5ZF/PXOO2TpbFj0BrV0SO+jhaRHL73BcCx593yJvQww5KLtzMP9NSkDSOZcsnMfyumgRInrw51uBA3+msKsTfiNIV+GfYQdgYXZTvublBnhHiC+x+lBoCmb9pq8ZNpVgDpGkA0QUEPP/6K+RKii3w0AK1Poh+NSwM/nwi2Hnbc+6gltxbR1otuNmYwbaU922eCKNQiemjS7Vrof/SYv0K+BvSFXA2GB/nTJCAQiBfyiUb0YMLWAOhAUOk0x21iZDV3paV+NV++89gtMm29eK6oyNHl9lSbpXteUk5F7FVrZzroSGOe2LLwqBjjhPgpMkeWMiL8iKjxn3OJ3mo5vzdbRlMYhaNmDz5993ny7ElBWrFENs+Rw18kYqtSqlbCns493yY8J73ZzfbAuR3lX//8EWYKlYIrEfQzEieORfmh8c1QvAXB9i/gRPamGcT9zBt7iy+spAhBJXbSORWr6t1k+NlNbTtH2OP/iKCBSI3eaiymNmzCi1HigfvI0tgFwd3bPmJcGMQ91fVfMeRopDNu7y
  template:
    metadata:
      creationTimestamp: null
      name: myinves-secrets
      namespace: myinves