apiVersion: v2
name: mtrack
description: Chart to deploy MTrack using generic applications chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: base-application
    alias: mtrack-be
    version: 0.1.0
    repository: "file://../../charts/applications"
    condition: mtrack-be.enabled
  - name: base-application
    alias: mtrack-fe
    version: 0.1.0
    repository: "file://../../charts/applications"
    condition: mtrack-fe.enabled