mtrack-be: 
  enabled: true
  fullnameOverride: mtrack-be


  image:
    registry: registry.agogi.dev
    repository: mtrack_be
    tag: "2.2.0"
    pullPolicy: Always

  replicaCount: 1

  service:
    enabled: true
    type: ClusterIP
    port: 8080
    targetPort: 8080

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-production-cluster-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
    className: "traefik"
    hosts:
      - host: api.mtrack.agogi.dev
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
        - api.mtrack.agogi.dev
        secretName: api.mtrack-tls-secret

  envFromSecrets:
    - name: mtrack-secrets

  env:
    # Postgres configuration
    - name: POSTGRESQL_HOST
      value: postgresql.postgres.svc.cluster.local
    - name: POSTGRESQL_PORT
      value: "5432"
    - name: POSTGRESQL_DATABASE
      value: mtrack
    - name: APP_URL
      value: https://mtrack.agogi.dev
    - name: ORBIT_API_URL
      value: https://api.orbit.agogi.dev/api/v1/register

mtrack-fe: 
  enabled: true
  fullnameOverride: mtrack-fe

  image:
    registry: registry.agogi.dev
    repository: mtrack_fe
    tag: "2.2.0"
    pullPolicy: Always

  replicaCount: 1

  service:
    enabled: true
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-production-cluster-issuer
      traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: default-authentik-redirect@kubernetescrd
    hosts:
      - host: mtrack.agogi.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
        - mtrack.agogi.dev
        secretName: mtrack-tls-secret

  env:
    - name: VITE_API_BASE_URL
      value: https://api.mtrack.agogi.dev
