apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-github-token
  namespace: n8n
spec:
  encryptedData:
    GITHUB_TOKEN: AgCYvzZrghtmD7DokBpk1EGHH7bBpn3DbdFmK4XrciYfRsGDSFnAfQ/x/JfMwutdxC+jIbHR6Bu5FRH1l6brt8SzOCw5iSGYayZbYKx9qK81sIqTxKKnkzOX+hYhHyKQ2LCTjF4689f1hZyk0uF65///ITsOjZyq0ZSyl0F5JBUY3i+YVkUTD6m1Uk+xXFHFNrQKV7Ttb0BLaU2ZWi9DazX3WO4IybIisujotZa8Str4PSU0r9DrnyG5YiiO7pn2EK/1qP7GSr7vYbp9rK7tvLbW62VfljjyO+/IPh367xkLpQyPwAqQ13SFIG5mdP8pkwZ4D/0SM6rrukpZSwJDBNrbz+9JCT0ykoIpkGhLZpme955AzgRP2G513VqgWrxDYJU6sCff3lyn6zLiLfHJROyioWtFFWjiSxayHhDnRbSIeMra+UHI/iBE5CogihJf7R0vAei9lI01NIaZEB8JtvGx7ioDp8MyKjEbUpuEnAMO+kfzK9ryIOrnRRn2Eu7dgI/lUqzh4ZjX8vzVZ5L9CYeoG+I2umOCCmaELC3Wm6DlgYunk9+/5z7okGiRWEVcAWwQYZvq7PKRsw688fbmwFbqG+PCV6qxe/3B1xuojenZJuRvi9hFo8SdiH5xkBD8voVWK+6KMjStkDVBEScbN5jo6NaVW9W34CFpAUJwe7RunBVuTZ20Xr7otFpItj65WloxNccCPfdF+gfcpGR+ce5w/SUgN8A7KBM7iSYrEfeR6ZsoaWijfD+rkzKrgN6exMKfu676AimyOxXWrxlHnaBDKK+ORkGlFsekmBOH/BbU6nOvqjiJckqMUYAjN0w=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-github-token
      namespace: n8n