apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-opencode-token
  namespace: n8n
spec:
  encryptedData:
    OPENCODE_API_KEY: AgCaSr77xROpe8Woggpf35ERWBGFFQNb2LSj0uU7JWk10Hm6GdIjD/plVWiPaCtAYUn5eRViLRjkC2NOcsjMo7IDG/U/9kMMcTIjsXCiYNcJwQi2JFgDZBz8yE1MBvG6IjN10TiKrfHp4OlAOcy/DwUgTtX21UD6N108KRo9xbsX0vlMZAHXW1EjgyfmRIG/uuBiJ0Jds26mabnoxAm3B57ylYQeZp2tks2HEC4hCr/5OAtZjiTHo+HPWhTknngRxYtp1+R2DRLFBTDOI0EvpiW6U1EtZICLT+q5lW1ibiyzh722OJ/5vQKx9pMHWqw6VEjuFMNZuya9jHF0xf2azpGRWdE4AZmbRwQxlTStQAlfsLD1NAoAM6zu4oBCbdwb+u53u5NXLGuRyc/6AO2WNZ0Nd7sDH495Gr/ib0rxOmbMbl60K/plj0k+I2Rbujts5u3pNNoSh/cIfvCG0IXbAArhKX0Z3GObZwAgqnTntK7CXEas9LdaXwQMigPsPeqnUXKFnC+jyBw+zqSP64/wPio+ybCyEFcPl909gCvhhhM5OH60lfA30dxZJoTTG0hrywB5ntbA95yLT/ucdAKqATlHzv3zhyWZk3A86jYyG3nYDo+ocSCOheW60dx/sy9s2Ne/q86U2EPb20E+8PL0ecAVLGiI5F13Q2isUnbZHP/aG0Faf5iFO3td+Fvx8TAceJ5+kZ1TNde/DbmqhrfbMbyCpzfQ/5qgBhThL7EDl24MLoyeouAmd5uhslRGCKquNB6RquI=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-opencode-token
      namespace: n8n