apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-runner-token
  namespace: n8n
spec:
  encryptedData:
    RUNNER_AUTH_TOKEN: AgCn3CnqvMnPiuXsJtgkhJM/h6xYS/zmyzI/NxbFRCZy996vRibtDSRT0vlve2Ih33MSJEG+OMXUhAhwaMMq4u+smgsek0HVZsOy9A71U8iU2oqUqdDFWW0A996vA+NTsrQnV2gwHnQecRxC6MO8iz/YEUBwu83Sf38XZYEml3M0d+oqq35nmha+ADbnfcJymKhVSMI3NgjluiG8IaOwc97FMi4+qwSHFo+lNleEktkLzYzQwNa+ehlrrvOSGV81DkszPLmUcC0okZRjRBU71k5TWDmnb+QADVywWxhF5AVpdUUTVyTHLSe4LLd57mm5Wex4dTyhrRRESEcNykVYlFGF4DRflDK4XTt20W2aRPJXqTKGNEZHmZanO8XstjameJ+lshRgueMob2dKf1d2w54xo2Fzwq5CW4gY/B65Nw9pFgplTQvpaTnrdo66dXpYzJ3k4pA7Vl7adfi/6Ag3+IirBqGzHePIVSChKsoeP1W4g12A9KiFcwAnq+FUfr5Q9kPHGxApzys1rHyuJwyHKPUEQ603SnE0gzdONeLX26O4okfNeECb36U2ixlI9Z888gRCNXLcmYxRxMEywMLp9biJnHH9+VtPAt8v7pkpXF0wbN+/sWNd3r+f8HYpRavbT4oVGiDdRili/R1bv81DIIClGQRE/B0lFu/pdT08qdgaG+OAxSYJNKN8DX1JXKrJ6wH2aE09TjMRn6JEc5pFrktJXy9Mc4jYXwsixLyYyWpgQgdVCC5DDNpW/ltiVnHqUHMfThO0iUBHwegyan4=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-runner-token
      namespace: n8n