apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-runner-token
  namespace: n8n
spec:
  encryptedData:
    N8N_RUNNERS_AUTH_TOKEN: AgBKkkJ138VAo02btkQ0huDYy750yvxBWjGGzM3xtCwSPqIRTe3ulU1qokdRdv8DE6dNXBxW5ToJg2+6y5MoCif4ITxs+QfRyjUUApINe/x78IgoqoDnzFpl5FP1bFbnlXtA9Ldg0Bh7HXQkBOH7sDl2GOUHhTMGwVvV6cA1OlbdTqXpo2dmA8hK/zWGgu7X6P5Yzy66Nx+9jUBNlDPNCWGoEK5EdXSp1jsGShHlBID6AJ1QtN16122Uh74zy7xadsLBbO5sSKatm7KI5FJpnr6YwNHOnQaNxhkGN487spcw1x+Vz9SUBNYaAFcoYS9owMyx2afaZbWQAM0m2EMOu5Pf3Uh6py/KI74354DVF+b7BXLsP8qpm/DlCljqa0gLgs8CsFwmzJ9+1A4tnStqQjhlnmXA0/V25DibHrGkMcVnzFxvevYmEiX7PWu4QXtAmbh+QZWrV9TkW97HH+F1DnLnHu4DTfXHSlhxpi/axciBKOUDnuHjGOIQpLdsIaIcmogq9q1IPl40ECU6i55VjP0GXYyg6NAeegwFKJg3MpxjUr6LdBiELNA2MA32eJqM44QMRwsC1KmoDXPw10bM7QS6Ie/b1G9Ljpih/WHwL23Kbm/WABqDAOzz3BmFag8qTNJ8Jn5m0dwe8UkH2xEDGd0VT0pTqzHabKYUwBji/UBAYVHwdOrqG5m+UYYhF7fewvKY5hMnOlS7RpGVFEgvfsFYK2ElLGhCLXrEe2FeCSZSLfYCASQT4CMdNISaSmCAr9twe+jW/4XKEZH8wyQ=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-runner-token
      namespace: n8n