ollama:  
  enabed: true

  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent

  replicaCount: 1

  models:
    path: /models
    pull:
      - llama3.2:3b-instruct-q4_K_M

  storage:
    enabled: true
    createPV: true
    storageClassName: "local-ssd"
    size: 100Gi
    hostPath: /mnt/ssd1/models

  service:
    type: NodePort
    port: 11434
    nodePort: 30434